name: Omur Oztas
favicon: null
layout_spectrum: 0.4327876982279122
typography_spectrum: 0.43675258895382285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8958027467597276
  lightness: 0.03368908213451505
  saturation: 0.6140185177791864
  rhythmicContrast: 0.881212413078174
purpose: []
